### ISSUE TITLE
Displaying GeoJSON points with markerCluster plugin

### ISSUE THREAD

**Issue by mixedbredie** [bmcbride/PHP-Database-GeoJSON#2]
Thanks for the very useful repo!

I want to use the Leaflet markerCluster plugin with GeoJSON points pulled from PostGIS. I think the markerCluster plugin needs to have all the data loaded first before it can cluster the points.  How do I change the $.GetJSON method to include the markerCluster functionality?  I've included a snippet of the code I am using with the markerCluster lines commented out:

    //var markers = new L.markerClusterGroup();
		
		// Define point symbol
		var lampfaultsdata_Icon = L.icon({
			iconUrl: 'icons/lampfaultsIcon.png',
			iconSize: [20, 30],
			iconAnchor: [12, 28],
			popupAnchor: [0, -25]
		});
		
		// Define GeoJSON data
		var lampfaultsdata =  L.geoJson(null, {
			pointToLayer: function (feature, latlng) { 
			  return L.marker(latlng, {
				icon: lampfaultsdata_Icon,
				title: feature.properties.assetname
			  });
			},
			onEachFeature: function (feature, layer) {
			  if (feature.properties) {
					var content = '<table border="1" style="border-collapse:collapse;" cellpadding="2">' +
					'<tr>' + '<th>Name</th>' + '<td><b>' + feature.properties.assetname + '</b></td>' + '</tr>' +
					'<tr>' + '<th>Date reported</th>' + '<td>' + feature.properties.faultdate + '</td>' + '</tr>' +
					'<tr>' + '<th>Fault Status</th>' + '<td>' + feature.properties.faultstatus + '</td>' + '</tr>' +
					'<tr>' + '<th>View Map</th>' + '<td>' + feature.properties.lamplocation + '</td>' + '</tr>' +
					'<table>';
				layer.bindPopup(content);
			  }
			}
		});
		
		// Get GeoJSON data from PostGIS
		$.getJSON("layers/lamp_faults_geojson.php", function (data) {
				lampfaultsdata.addData(data);
				//markers.addLayer(lampfaultsdata);
				//map.addLayer(markers);
			}).complete(function () {
				map.fitBounds(lampfaultsdata.getBounds());
		});

In this case I am wanting to show faulty street lamps and I think I need to do something like this but can't work out where to fit it in:

    		lampfaultsdata.on('data:loaded', function () {
			markers.addLayer(lampfaultsdata);
			map.addLayer(markers);
		});
		
		lampfaultsdata.on('data:loaded', function () {
			map.fitBounds(lampfaultsdata.getBounds());
			}.bind());

Any pointers gratefully received.

**Comment by bmcbride** [comment]
Sorry I'm just getting to this- have you figured it out or are you still struggling? If so, do you have a live site or jsFiddle I could look at to help debug?

**Comment by mixedbredie** [comment]
Thanks for getting back to me - not cracked it yet.

Here is a jsFiddle - http://fiddle.jshell.net/jpxzdvbp/ - you'll notice I am working in EPSG:27700 (British National Grid) hence the proj4 links. If I export my data to a JSON file and load it in a leaflet map with the cluster plugin then the clustering works fine.  Just seems to be the GeoJSON coming from PostGIS that's giving issues.  Does all the data need to be loaded before the clustering plugin works?

This is what the map looks like

![leaflet-map](https://cloud.githubusercontent.com/assets/3995787/7911301/15d41f9a-0854-11e5-81fa-99ff53ee2632.jpg)

**Comment by bmcbride** [comment]
Couldn't get your fiddle to work, but I added a clustering layer example to the demo to show how it would work. See https://github.com/bmcbride/PHP-Database-GeoJSON/blob/master/demo/index.html#L67-L76. Basically, after you've added the features to the GeoJSON layer, you add that layer to the MarkerClusterGroup. Make sense?

**Comment by mixedbredie** [comment]
That's worked perfectly! Thank you.
I'll have to work out how to use jsFiddle properly now.

**Comment by bmcbride** [comment]
Great to hear!
