### ISSUE TITLE
sql injection

### ISSUE THREAD

**Issue by geosmiles** [bmcbride/PHP-Database-GeoJSON#3]
Hi. I've been playing around with you code and producting some nice maps. However I showed your php to a friend who is hot on the subject and he said that this it would be easy to do sql injection to drop tables etc. Any thoughts on the subject, as I'd like to continue using your code for a map production piece I'm working on.

**Comment by bmcbride** [comment]
Use a database user with read only privileges.

**Comment by geosmiles** [comment]
Have a read of http://www.w3schools.com/sql/sql_injection.asp I don't think it is a simple as setting database user privileges.

**Comment by geosmiles** [comment]
A read only connection wont prevent a database dump unfortunately, however adding in stored procedures, such as these might help?  

$query = ‘SELECT …. WHERE public.ST_Transform(the_geom, 4326) && public.ST_SetSRID(public.ST_MakeBox2D(public.ST_Point($1,$2), public.ST_Point($3,$4)),4326)’;

$array = ($_REQUEST[bbox1],$_REQUEST[bbox2],$_REQUEST[bbox3],$_REQUEST[bbox4]);

$result = pg_query_params(CONNECTION, $query, $array)
